apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-demo-ingress
  namespace: awx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # Use HTTP for ingress-to-backend communication
    nginx.ingress.kubernetes.io/ssl-redirect: "true"         # Force SSL redirection for clients
spec:
  ingressClassName: public
  tls:
    - secretName: awx-demo-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-demo-service
                port:
                  number: 80

